name: NestJS Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/lms-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/lms-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lms_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.7'  # Specific version to match cache
        cache: 'npm'
        cache-dependency-path: 'backend/lms-backend/package-lock.json'
    
    - name: Generate package-lock.json if missing
      run: |
        cd backend/lms-backend
        if [ ! -f "package-lock.json" ]; then
          npm install --package-lock-only
        fi
        
    - name: Install dependencies
      run: |
        cd backend/lms-backend
        npm ci
    
    - name: Lint
      run: |
        cd backend/lms-backend
        npm run lint
        
    - name: Run tests
      run: |
        cd backend/lms-backend
        npm run test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/lms_db
        
    - name: Build application
      run: |
        cd backend/lms-backend
        npm run build
