name: NestJS Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/lms-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/lms-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lms_db
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Verify Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        check-latest: true
        
    - name: Generate package-lock.json if missing
      run: |
        cd backend/lms-backend
        if [ ! -f "package-lock.json" ]; then
          npm install --package-lock-only
        fi
        
    - name: Install dependencies
      run: |
        cd backend/lms-backend
        npm ci
