name: Flutter Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/lms/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/lms/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'  # Updated to match the required SDK version
        channel: 'stable'
        cache: true

    - name: Verify Flutter and Dart versions
      run: |
        flutter --version
        dart --version

    - name: Install dependencies
      run: |
        cd frontend/lms
        flutter pub get
        
    - name: Analyze code
      run: |
        cd frontend/lms
        flutter analyze
        
    - name: Run tests
      run: |
        cd frontend/lms
        flutter test --coverage
        
    - name: Build web (for verification)
      run: |
        cd frontend/lms
        flutter build web --release
        
    - name: Build Android APK (for verification)
      run: |
        cd frontend/lms
        flutter build apk --release
